name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      # Start the server in the background
      - name: Start server
        run: npm start &
        env:
          PORT: 3000

      # Wait for the server to start
      - name: Wait for server
        run: sleep 5

      # Install Lighthouse
      - run: npm install && npm install -g @lhci/cli@0.14.x
      - run: npm run build
      - run: lhci autorun
